### ISSUE TITLE
About the dataset of this paper

### ISSUE THREAD

**Issue by Lunarscave** [RyuZhihao123/ISMAR_Building#1]
I wonder know the dataset of this paper(includes the classify between buildingmass, roof or stairs and the pointNet training dataset)
maybe something unpublished, it's very pleasure to share them with me.
: ) have fun

**Comment by RyuZhihao123** [comment]
Regarding dataset: 
You can search for "procedural modeling" techniques, especially referring to this paper [1]. This is a rather traditional computer graphics algorithm. Through adjusting L-system grammars, you can **automatically** generate a large number of 3D building models very fast. Once you get the hierarchy/mesh of the buildings, you can easily extract any desired information (including edges and corners). Certainly, you can also jitter the edges to approximately simulate the human-drawn strokes.

[1] Talton et al. Metropolis Procedural Modeling. ACM SIGGRAPH (Transactions on Graphics).

**Comment by RyuZhihao123** [comment]
<img width="649" alt="building" src="https://github.com/RyuZhihao123/ISMAR_Building/assets/31232201/6ed98601-0940-46cc-9ff0-c1136e4d9fe1">

For your information, I attached some buildings that were generated by my implemented L-system algorithm, which is indeed a powerful approach to rapidly generate numerous 3D models.
Thus, I strongly recommend you try the algorithm in the paper [1] as well if you would like to do some building-related stuff. 

But.... I am afraid that you may have to re-implement it from scratch, because unfortunately, many CG (graphics) researches are not open-source. They typically involve heavy workloads and huge programming efforts, thereby making them valuable properties to the owners.

**Comment by RyuZhihao123** [comment]
If you need further information, you can leave your **WeChat ID 微信** here (I guess you're chinese too? or at least study in CN).

I will contact you very soon after you get back to me. (I will delete the message with your Wechat ID once it's done).

Wish you a happy new year.

**Comment by Lunarscave** [comment]
Thank you for your detailed reply! Yep,  Im chinese (maybe my Eng. is poor lol). I would appreciate it if you would help me out.
My mobile phone number is 18759180231, and u can add my WeChat though it.
Happy New Year! The same to you!
